name: tilbot
services:
  vector-similarity-intent:
    build:
      context: .
      args:
        PORT: ${PORT}      
    restart: unless-stopped
    environment:
      MODELNAME: ${MODELNAME}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app