name: tilbot
services:
  vector-similarity-intent:
    build:
      context: .
      args:
        PORT: ${PORT}      
    restart: unless-stopped
    environment:
      MODELNAME: "NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers"
      PORT: 8081
    ports:
      - 8081:8081
    volumes:
      - .:/app